[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.14.36", features = ["ttf"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5.0"
