[workspace]
members = [".", "rustleaf-macros"]

[package]
name = "rustleaf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustleaf"
path = "src/main.rs"

[lib]
name = "rustleaf"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.0", features = ["derive"] }
indexmap = "2"
rustleaf-macros = { path = "rustleaf-macros" }

[dev-dependencies]
tempfile = "3.0"